-- XPLMS migration 004: expanded progress, XP proof claims and quizzes

begin;

alter table public.stud_progress
  add column if not exists "INDIVIDUAL ASSIGNMENT" numeric,
  add column if not exists "GROUP ASSIGNMENT" numeric,
  add column if not exists "UPS 1" numeric,
  add column if not exists "UPS 2" numeric,
  add column if not exists "UPS 3" numeric;

update public.xp_rules
set active = false, updated_at = now()
where code in ('discipline', 'earliest_submission');

insert into public.xp_rules (code, name, description, award_mode, default_points)
values
  ('math_discussion', 'Mathematics discussion', 'Approved evidence of a meaningful mathematics discussion.', 'manual', 20),
  ('quiz_completion', 'In-app quiz', 'Successful completion of a material-based XPLMS quiz.', 'automatic', 25)
on conflict (code) do update
set name = excluded.name,
    description = excluded.description,
    default_points = excluded.default_points,
    active = true,
    updated_at = now();

create table if not exists public.xp_claims (
  id bigint generated by default as identity primary key,
  student_user_id uuid not null references public.app_users(id) on delete cascade,
  "NO MATRIK" text not null references public.app_users("NO MATRIK") on update cascade,
  claim_type text not null default 'math_discussion'
    check (claim_type in ('math_discussion')),
  title text not null,
  description text not null,
  proof_path text not null,
  status text not null default 'pending'
    check (status in ('pending','approved','rejected')),
  admin_note text,
  reviewed_by uuid references public.app_users(id) on delete set null,
  reviewed_at timestamptz,
  xp_event_id bigint references public.xp_events(id),
  created_at timestamptz not null default now()
);

create table if not exists public.quizzes (
  id bigint generated by default as identity primary key,
  material_id bigint references public.materials(id) on delete set null,
  title text not null,
  instructions text,
  xp_reward integer not null default 25 check (xp_reward >= 0),
  passing_score numeric not null default 60 check (passing_score between 0 and 100),
  status text not null default 'draft' check (status in ('draft','published','archived')),
  generated_by_ai boolean not null default false,
  created_by uuid references public.app_users(id) on delete set null,
  created_at timestamptz not null default now()
);

create table if not exists public.quiz_questions (
  id bigint generated by default as identity primary key,
  quiz_id bigint not null references public.quizzes(id) on delete cascade,
  position integer not null,
  question text not null,
  options jsonb not null,
  correct_index integer not null check (correct_index between 0 and 3),
  explanation text not null,
  unique (quiz_id, position)
);

create table if not exists public.quiz_attempts (
  id bigint generated by default as identity primary key,
  quiz_id bigint not null references public.quizzes(id) on delete cascade,
  student_user_id uuid not null references public.app_users(id) on delete cascade,
  "NO MATRIK" text not null references public.app_users("NO MATRIK") on update cascade,
  answers jsonb not null,
  score numeric not null check (score between 0 and 100),
  correct_count integer not null,
  total_questions integer not null,
  passed boolean not null,
  xp_event_id bigint references public.xp_events(id),
  completed_at timestamptz not null default now(),
  unique (quiz_id, student_user_id)
);

insert into storage.buckets (id, name, public)
values ('xp-proofs', 'xp-proofs', false)
on conflict (id) do nothing;

alter table public.xp_claims enable row level security;
alter table public.quizzes enable row level security;
alter table public.quiz_questions enable row level security;
alter table public.quiz_attempts enable row level security;

revoke all on table
  public.xp_claims,
  public.quizzes,
  public.quiz_questions,
  public.quiz_attempts
from anon, authenticated;

commit;
