-- XPLMS migration 026: privacy-safe Realtime wake-up events for Battle only.
-- Run after migration 025. Actual battle records remain server-only.

begin;

create table if not exists public.battle_realtime_channels (
  student_user_id uuid primary key references public.app_users(id) on delete cascade,
  channel_key uuid not null unique default gen_random_uuid(),
  created_at timestamptz not null default now()
);

create table if not exists public.battle_realtime_events (
  id bigint generated by default as identity primary key,
  channel_key uuid not null,
  event_type text not null,
  created_at timestamptz not null default clock_timestamp()
);

create index if not exists battle_realtime_events_channel_idx
  on public.battle_realtime_events(channel_key, id desc);

insert into public.battle_realtime_channels(student_user_id)
select id from public.app_users where role = 'student' and active = true
on conflict (student_user_id) do nothing;

alter table public.battle_realtime_channels enable row level security;
alter table public.battle_realtime_events enable row level security;
revoke all on table public.battle_realtime_channels from anon, authenticated;
revoke all on table public.battle_realtime_events from anon, authenticated;
grant select on table public.battle_realtime_events to anon;

drop policy if exists battle_realtime_events_are_notification_only
  on public.battle_realtime_events;
create policy battle_realtime_events_are_notification_only
on public.battle_realtime_events for select to anon using (true);

create or replace function public.ensure_battle_realtime_channel(p_student_user_id uuid)
returns uuid
language plpgsql
security definer
set search_path = public
as $$
declare result_key uuid;
begin
  insert into public.battle_realtime_channels(student_user_id)
  values (p_student_user_id)
  on conflict (student_user_id) do nothing;
  select channel_key into result_key from public.battle_realtime_channels
  where student_user_id = p_student_user_id;
  return result_key;
end;
$$;

create or replace function public.emit_battle_realtime_event(
  p_student_user_id uuid,
  p_event_type text
)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare target_key uuid;
begin
  target_key := public.ensure_battle_realtime_channel(p_student_user_id);
  insert into public.battle_realtime_events(channel_key, event_type)
  values (target_key, p_event_type);
  delete from public.battle_realtime_events
  where created_at < now() - interval '1 day';
end;
$$;

create or replace function public.notify_battle_challenge_change()
returns trigger language plpgsql security definer set search_path = public as $$
begin
  perform public.emit_battle_realtime_event(new.challenger_id, 'challenge');
  perform public.emit_battle_realtime_event(new.opponent_id, 'challenge');
  return new;
end;
$$;

drop trigger if exists notify_battle_challenge_change on public.battle_challenges;
create trigger notify_battle_challenge_change
after insert or update on public.battle_challenges
for each row execute function public.notify_battle_challenge_change();

create or replace function public.notify_battle_match_change()
returns trigger language plpgsql security definer set search_path = public as $$
begin
  perform public.emit_battle_realtime_event(new.player_a_id, 'match');
  perform public.emit_battle_realtime_event(new.player_b_id, 'match');
  return new;
end;
$$;

drop trigger if exists notify_battle_match_change on public.battle_matches;
create trigger notify_battle_match_change
after insert or update on public.battle_matches
for each row execute function public.notify_battle_match_change();

create or replace function public.notify_battle_answer_change()
returns trigger language plpgsql security definer set search_path = public as $$
declare match_row public.battle_matches%rowtype;
begin
  select * into match_row from public.battle_matches where id = new.battle_id;
  perform public.emit_battle_realtime_event(match_row.player_a_id, 'answer');
  perform public.emit_battle_realtime_event(match_row.player_b_id, 'answer');
  return new;
end;
$$;

drop trigger if exists notify_battle_answer_change on public.battle_answers;
create trigger notify_battle_answer_change
after insert or update on public.battle_answers
for each row execute function public.notify_battle_answer_change();

create or replace function public.notify_battle_ready_change()
returns trigger language plpgsql security definer set search_path = public as $$
declare match_row public.battle_matches%rowtype;
begin
  select * into match_row from public.battle_matches where id = new.battle_id;
  perform public.emit_battle_realtime_event(match_row.player_a_id, 'ready');
  perform public.emit_battle_realtime_event(match_row.player_b_id, 'ready');
  return new;
end;
$$;

drop trigger if exists notify_battle_ready_change on public.battle_round_ready;
create trigger notify_battle_ready_change
after insert or update on public.battle_round_ready
for each row execute function public.notify_battle_ready_change();

do $$
begin
  if not exists (
    select 1 from pg_publication_tables
    where pubname = 'supabase_realtime'
      and schemaname = 'public'
      and tablename = 'battle_realtime_events'
  ) then
    alter publication supabase_realtime add table public.battle_realtime_events;
  end if;
end;
$$;

commit;
