-- XPLMS migration 002: application-managed authentication
-- This removes the runtime dependency on Supabase Auth.
-- Passwords are bcrypt hashes generated by the Streamlit server.

begin;

create table if not exists public.app_users (
  id uuid primary key default gen_random_uuid(),
  email text not null,
  full_name text not null,
  role text not null check (role in ('student','lecturer','admin')),
  "NO MATRIK" text unique,
  password_hash text not null,
  active boolean not null default true,
  must_change_password boolean not null default true,
  last_login_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint app_users_email_lower_unique unique (email),
  constraint app_users_student_matric_check check (
    (role = 'student' and "NO MATRIK" is not null)
    or (role in ('lecturer','admin') and "NO MATRIK" is null)
  )
);

create unique index if not exists app_users_email_ci_unique
on public.app_users (lower(email));

alter table public.app_users enable row level security;
revoke all on table public.app_users from anon, authenticated;

-- Repoint application ownership from auth.users/profiles to app_users.
alter table public.assignments
  drop constraint if exists assignments_lecturer_id_fkey;
alter table public.assignments
  add constraint assignments_lecturer_id_fkey
  foreign key (lecturer_id) references public.app_users(id) on delete set null;

alter table public.materials
  drop constraint if exists materials_lecturer_id_fkey;
alter table public.materials
  add constraint materials_lecturer_id_fkey
  foreign key (lecturer_id) references public.app_users(id) on delete set null;

alter table public.submissions
  drop constraint if exists submissions_student_user_id_fkey;
alter table public.submissions
  drop constraint if exists "submissions_NO MATRIK_fkey";
alter table public.submissions
  drop constraint if exists submissions_no_matrik_fkey;
alter table public.submissions
  add constraint submissions_student_user_id_fkey
  foreign key (student_user_id) references public.app_users(id) on delete cascade;
alter table public.submissions
  add constraint submissions_NO_MATRIK_fkey
  foreign key ("NO MATRIK") references public.app_users("NO MATRIK") on update cascade;

alter table public.xp_events
  drop constraint if exists "xp_events_NO MATRIK_fkey";
alter table public.xp_events
  drop constraint if exists xp_events_no_matrik_fkey;
alter table public.xp_events
  drop constraint if exists xp_events_awarded_by_fkey;
alter table public.xp_events
  add constraint xp_events_NO_MATRIK_fkey
  foreign key ("NO MATRIK") references public.app_users("NO MATRIK") on update cascade;
alter table public.xp_events
  add constraint xp_events_awarded_by_fkey
  foreign key (awarded_by) references public.app_users(id) on delete set null;

-- Supabase-Auth-based functions are no longer used by the application.
drop function if exists public.award_manual_xp(text, text, text, integer, text);
drop function if exists public.award_earliest_submission_xp(bigint);

commit;
