-- XPLMS migration 018
-- Persist one unique 10-question combination per student, chapter and day.

begin;

create table if not exists public.daily_quiz_sets (
  id bigint generated by default as identity primary key,
  student_user_id uuid not null
    references public.app_users(id) on delete cascade,
  "NO MATRIK" text not null,
  chapter integer not null check (chapter in (1, 2, 5, 8, 9, 10)),
  set_date date not null,
  question_ids bigint[] not null
    check (cardinality(question_ids) = 10),
  set_fingerprint text not null,
  created_at timestamptz not null default now(),
  unique (student_user_id, chapter, set_date),
  unique (chapter, set_date, set_fingerprint)
);

create index if not exists daily_quiz_sets_student_history_idx
  on public.daily_quiz_sets (student_user_id, chapter, set_date desc);

alter table public.daily_quiz_sets enable row level security;
revoke all on table public.daily_quiz_sets from anon, authenticated;

commit;
