-- XPLMS migration 019
-- Refresh-safe application sessions and accurate XP badge achievement times.
-- Run once in the Supabase SQL Editor after migration 018.

begin;

create table if not exists public.app_sessions (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.app_users(id) on delete cascade,
  token_hash text not null unique,
  created_at timestamptz not null default now(),
  expires_at timestamptz not null,
  revoked_at timestamptz
);

create index if not exists app_sessions_active_token_idx
  on public.app_sessions (token_hash, expires_at)
  where revoked_at is null;

alter table public.app_sessions enable row level security;
revoke all on table public.app_sessions from anon, authenticated;

-- The XP event's created_at is the time the qualifying activity/request occurred.
-- Approval only determines whether that event is inserted; it does not replace
-- the original activity timestamp.
create or replace function public.capture_xp_badges()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  current_xp integer;
begin
  select coalesce("XP", 0) into current_xp
  from public.stud_xp
  where "NO MATRIK" = new."NO MATRIK";

  insert into public.student_badges (
    "NO MATRIK", badge_family, badge_code, badge_name,
    xp_threshold, source_xp_event_id, earned_at
  )
  select
    new."NO MATRIK", 'xp', level.badge_code, level.badge_name,
    level.threshold, new.id, coalesce(new.created_at, now())
  from (
    values
      ('rookie', 'Rookie', 200),
      ('explorer', 'Explorer', 500),
      ('expert', 'Expert', 1000),
      ('legend', 'Legend', 1500)
  ) as level(badge_code, badge_name, threshold)
  where current_xp >= level.threshold
  on conflict ("NO MATRIK", badge_family, badge_code) do nothing;
  return new;
end;
$$;

-- Correct existing XP badge timestamps to the first event at which the
-- student's running XP reached the corresponding threshold.
with running_xp as (
  select
    id,
    "NO MATRIK",
    created_at,
    sum(points) over (
      partition by "NO MATRIK"
      order by created_at, id
      rows between unbounded preceding and current row
    ) as running_total
  from public.xp_events
), first_crossing as (
  select
    sb.id as badge_id,
    min(rx.created_at) as achieved_at
  from public.student_badges sb
  join running_xp rx
    on rx."NO MATRIK" = sb."NO MATRIK"
   and rx.running_total >= sb.xp_threshold
  where sb.badge_family = 'xp'
  group by sb.id
)
update public.student_badges sb
set earned_at = fc.achieved_at
from first_crossing fc
where sb.id = fc.badge_id
  and fc.achieved_at is not null;

commit;
