-- XPLMS migration 013
-- Introduces qualifying-day streaks and permanent XP/Streak badge families.
-- Review and run once in Supabase SQL Editor after migrations 001-012.

begin;

create table if not exists public.student_activity_days (
  id bigint generated by default as identity primary key,
  "NO MATRIK" text not null,
  activity_date date not null,
  activity_type text not null check (
    activity_type in ('in_app_quiz', 'extra_practice')
  ),
  source_id text not null,
  created_at timestamptz not null default now(),
  unique ("NO MATRIK", activity_type, source_id)
);

create index if not exists student_activity_days_streak_idx
  on public.student_activity_days ("NO MATRIK", activity_date desc);

alter table public.student_activity_days enable row level security;
revoke all on table public.student_activity_days from anon, authenticated;

create or replace function public.current_student_streak(p_no_matrik text)
returns integer
language plpgsql
stable
security definer
set search_path = public
as $$
declare
  malaysia_today date := (now() at time zone 'Asia/Kuala_Lumpur')::date;
  target_date date;
  streak integer := 0;
begin
  if exists (
    select 1 from public.student_activity_days
    where "NO MATRIK" = p_no_matrik and activity_date = malaysia_today
  ) then
    target_date := malaysia_today;
  elsif exists (
    select 1 from public.student_activity_days
    where "NO MATRIK" = p_no_matrik and activity_date = malaysia_today - 1
  ) then
    -- Today remains available until the Malaysia calendar day finishes.
    target_date := malaysia_today - 1;
  else
    return 0;
  end if;

  while exists (
    select 1 from public.student_activity_days
    where "NO MATRIK" = p_no_matrik and activity_date = target_date
  ) loop
    streak := streak + 1;
    target_date := target_date - 1;
  end loop;
  return streak;
end;
$$;

create or replace function public.longest_student_streak(p_no_matrik text)
returns integer
language sql
stable
security definer
set search_path = public
as $$
  with days as (
    select distinct activity_date
    from public.student_activity_days
    where "NO MATRIK" = p_no_matrik
  ),
  islands as (
    select
      activity_date,
      activity_date
        - (row_number() over (order by activity_date))::integer as island
    from days
  )
  select coalesce(max(day_count), 0)::integer
  from (
    select count(*) as day_count
    from islands
    group by island
  ) grouped_days;
$$;

create or replace view public.student_streak_summary
with (security_invoker = false)
as
select
  sb."NO MATRIK",
  public.current_student_streak(sb."NO MATRIK") as current_streak,
  public.longest_student_streak(sb."NO MATRIK") as longest_streak,
  (
    select max(sad.activity_date)
    from public.student_activity_days sad
    where sad."NO MATRIK" = sb."NO MATRIK"
  ) as last_activity_date
from public.stud_background sb;

revoke all on public.student_streak_summary from anon, authenticated;

create or replace function public.record_quiz_streak_day()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.student_activity_days (
    "NO MATRIK", activity_date, activity_type, source_id
  )
  values (
    new."NO MATRIK",
    (coalesce(new.completed_at, now()) at time zone 'Asia/Kuala_Lumpur')::date,
    'in_app_quiz',
    new.id::text
  )
  on conflict ("NO MATRIK", activity_type, source_id) do nothing;
  return new;
end;
$$;

drop trigger if exists record_quiz_streak_day on public.quiz_attempts;
create trigger record_quiz_streak_day
after insert on public.quiz_attempts
for each row execute function public.record_quiz_streak_day();

create or replace function public.record_extra_practice_streak_day()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  if new.claim_type = 'extra_practice' and new.status = 'approved' then
    insert into public.student_activity_days (
      "NO MATRIK", activity_date, activity_type, source_id
    )
    values (
      new."NO MATRIK",
      (new.created_at at time zone 'Asia/Kuala_Lumpur')::date,
      'extra_practice',
      new.id::text
    )
    on conflict ("NO MATRIK", activity_type, source_id) do nothing;
  end if;
  return new;
end;
$$;

drop trigger if exists record_extra_practice_streak_day on public.xp_claims;
create trigger record_extra_practice_streak_day
after insert or update of status, claim_type on public.xp_claims
for each row execute function public.record_extra_practice_streak_day();

alter table public.student_badges
  add column if not exists badge_family text not null default 'xp',
  add column if not exists streak_threshold integer,
  add column if not exists source_activity_id bigint
    references public.student_activity_days(id) on delete set null;

alter table public.student_badges
  alter column xp_threshold drop not null;

alter table public.student_badges
  drop constraint if exists student_badges_badge_code_check;
alter table public.student_badges
  drop constraint if exists student_badges_xp_threshold_check;

do $$
declare
  constraint_name text;
begin
  for constraint_name in
    select conname
    from pg_constraint
    where conrelid = 'public.student_badges'::regclass
      and contype = 'u'
      and pg_get_constraintdef(oid) like '%badge_code%'
      and conname <> 'student_badges_family_code_key'
  loop
    execute format(
      'alter table public.student_badges drop constraint %I',
      constraint_name
    );
  end loop;
end;
$$;

do $$
begin
  if not exists (
    select 1 from pg_constraint
    where conrelid = 'public.student_badges'::regclass
      and conname = 'student_badges_family_check'
  ) then
    alter table public.student_badges
      add constraint student_badges_family_check
      check (badge_family in ('xp', 'streak'));
  end if;
  if not exists (
    select 1 from pg_constraint
    where conrelid = 'public.student_badges'::regclass
      and conname = 'student_badges_threshold_check'
  ) then
    alter table public.student_badges
      add constraint student_badges_threshold_check
      check (
        (badge_family = 'xp' and xp_threshold > 0 and streak_threshold is null)
        or
        (badge_family = 'streak' and streak_threshold > 0 and xp_threshold is null)
      );
  end if;
  if not exists (
    select 1 from pg_constraint
    where conrelid = 'public.student_badges'::regclass
      and conname = 'student_badges_family_code_key'
  ) then
    alter table public.student_badges
      add constraint student_badges_family_code_key
      unique ("NO MATRIK", badge_family, badge_code);
  end if;
end;
$$;

create or replace function public.capture_xp_badges()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  current_xp integer;
begin
  select coalesce("XP", 0) into current_xp
  from public.stud_xp
  where "NO MATRIK" = new."NO MATRIK";

  insert into public.student_badges (
    "NO MATRIK", badge_family, badge_code, badge_name,
    xp_threshold, source_xp_event_id
  )
  select
    new."NO MATRIK", 'xp', level.badge_code, level.badge_name,
    level.threshold, new.id
  from (
    values
      ('rookie', 'Rookie', 100),
      ('explorer', 'Explorer', 300),
      ('expert', 'Expert', 600),
      ('legend', 'Legend', 1000)
  ) as level(badge_code, badge_name, threshold)
  where current_xp >= level.threshold
  on conflict ("NO MATRIK", badge_family, badge_code) do nothing;
  return new;
end;
$$;

create or replace function public.capture_streak_badges()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  current_streak integer;
begin
  current_streak := public.current_student_streak(new."NO MATRIK");
  insert into public.student_badges (
    "NO MATRIK", badge_family, badge_code, badge_name,
    streak_threshold, source_activity_id
  )
  select
    new."NO MATRIK", 'streak', level.badge_code, level.badge_name,
    level.threshold, new.id
  from (
    values
      ('rookie', 'Rookie', 7),
      ('explorer', 'Explorer', 14),
      ('expert', 'Expert', 21),
      ('legend', 'Legend', 28)
  ) as level(badge_code, badge_name, threshold)
  where current_streak >= level.threshold
  on conflict ("NO MATRIK", badge_family, badge_code) do nothing;
  return new;
end;
$$;

drop trigger if exists capture_streak_badges on public.student_activity_days;
create trigger capture_streak_badges
after insert on public.student_activity_days
for each row execute function public.capture_streak_badges();

-- Backfill qualifying days from existing quiz attempts and approved requests.
insert into public.student_activity_days (
  "NO MATRIK", activity_date, activity_type, source_id
)
select
  qa."NO MATRIK",
  (qa.completed_at at time zone 'Asia/Kuala_Lumpur')::date,
  'in_app_quiz',
  qa.id::text
from public.quiz_attempts qa
on conflict ("NO MATRIK", activity_type, source_id) do nothing;

insert into public.student_activity_days (
  "NO MATRIK", activity_date, activity_type, source_id
)
select
  xc."NO MATRIK",
  (xc.created_at at time zone 'Asia/Kuala_Lumpur')::date,
  'extra_practice',
  xc.id::text
from public.xp_claims xc
where xc.claim_type = 'extra_practice'
  and xc.status = 'approved'
on conflict ("NO MATRIK", activity_type, source_id) do nothing;

insert into public.student_badges (
  "NO MATRIK", badge_family, badge_code, badge_name, streak_threshold
)
select
  ss."NO MATRIK", 'streak', level.badge_code, level.badge_name, level.threshold
from public.student_streak_summary ss
cross join (
  values
    ('rookie', 'Rookie', 7),
    ('explorer', 'Explorer', 14),
    ('expert', 'Expert', 21),
    ('legend', 'Legend', 28)
) as level(badge_code, badge_name, threshold)
where ss.longest_streak >= level.threshold
on conflict ("NO MATRIK", badge_family, badge_code) do nothing;

commit;
