-- XPLMS migration 010
-- Permanently records individual badges once their overall XP threshold is met.

begin;

create table if not exists public.student_badges (
  id bigint generated by default as identity primary key,
  "NO MATRIK" text not null,
  badge_code text not null check (
    badge_code in ('rookie', 'explorer', 'expert', 'legend')
  ),
  badge_name text not null,
  xp_threshold integer not null check (xp_threshold > 0),
  earned_at timestamptz not null default now(),
  source_xp_event_id bigint references public.xp_events(id) on delete set null,
  unique ("NO MATRIK", badge_code)
);

create index if not exists student_badges_matric_earned_idx
  on public.student_badges ("NO MATRIK", earned_at);

alter table public.student_badges enable row level security;
revoke all on table public.student_badges from anon, authenticated;

create or replace function public.capture_xp_badges()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  current_xp integer;
begin
  select coalesce("XP", 0)
  into current_xp
  from public.stud_xp
  where "NO MATRIK" = new."NO MATRIK";

  if current_xp >= 100 then
    insert into public.student_badges (
      "NO MATRIK", badge_code, badge_name, xp_threshold, source_xp_event_id
    )
    values (new."NO MATRIK", 'rookie', 'Rookie', 100, new.id)
    on conflict ("NO MATRIK", badge_code) do nothing;
  end if;

  if current_xp >= 300 then
    insert into public.student_badges (
      "NO MATRIK", badge_code, badge_name, xp_threshold, source_xp_event_id
    )
    values (new."NO MATRIK", 'explorer', 'Explorer', 300, new.id)
    on conflict ("NO MATRIK", badge_code) do nothing;
  end if;

  if current_xp >= 600 then
    insert into public.student_badges (
      "NO MATRIK", badge_code, badge_name, xp_threshold, source_xp_event_id
    )
    values (new."NO MATRIK", 'expert', 'Expert', 600, new.id)
    on conflict ("NO MATRIK", badge_code) do nothing;
  end if;

  if current_xp >= 1000 then
    insert into public.student_badges (
      "NO MATRIK", badge_code, badge_name, xp_threshold, source_xp_event_id
    )
    values (new."NO MATRIK", 'legend', 'Legend', 1000, new.id)
    on conflict ("NO MATRIK", badge_code) do nothing;
  end if;

  return new;
end;
$$;

drop trigger if exists zz_capture_xp_badges on public.xp_events;
create trigger zz_capture_xp_badges
after insert on public.xp_events
for each row execute function public.capture_xp_badges();

-- Backfill badges already earned before this migration. Historical peak XP is
-- considered so an earlier deduction does not erase a previously reached level.
with running_xp as (
  select
    "NO MATRIK",
    sum(points) over (
      partition by "NO MATRIK"
      order by created_at, id
      rows between unbounded preceding and current row
    ) as running_total
  from public.xp_events
),
historical_peak as (
  select "NO MATRIK", max(running_total) as peak_xp
  from running_xp
  group by "NO MATRIK"
),
student_peak as (
  select
    sx."NO MATRIK",
    greatest(coalesce(sx."XP", 0), coalesce(hp.peak_xp, 0)) as peak_xp
  from public.stud_xp sx
  left join historical_peak hp using ("NO MATRIK")
),
badge_levels (badge_code, badge_name, xp_threshold) as (
  values
    ('rookie', 'Rookie', 100),
    ('explorer', 'Explorer', 300),
    ('expert', 'Expert', 600),
    ('legend', 'Legend', 1000)
)
insert into public.student_badges (
  "NO MATRIK", badge_code, badge_name, xp_threshold
)
select
  sp."NO MATRIK", bl.badge_code, bl.badge_name, bl.xp_threshold
from student_peak sp
cross join badge_levels bl
where sp.peak_xp >= bl.xp_threshold
on conflict ("NO MATRIK", badge_code) do nothing;

commit;
