-- XPLMS database extension
-- Run once in the Supabase SQL Editor. Existing stud_background and
-- stud_progress tables are intentionally not modified.
--
-- Student identity model:
--   "NO MATRIK"     = institutional student identifier shared by
--                     stud_background and stud_progress.
--   id/user UUID    = Supabase Auth identifier used only for authentication
--                     and row-level security.

create extension if not exists "pgcrypto";

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  full_name text not null,
  role text not null default 'student' check (role in ('student','lecturer','admin')),
  "NO MATRIK" text unique,
  created_at timestamptz not null default now()
);

create or replace function public.handle_new_user() returns trigger
language plpgsql security definer set search_path = public
as $$
begin
  insert into public.profiles (id, full_name, role, "NO MATRIK")
  values (
    new.id,
    coalesce(new.raw_user_meta_data->>'full_name', split_part(new.email, '@', 1)),
    case when new.raw_user_meta_data->>'role' in ('student','lecturer','admin')
      then new.raw_user_meta_data->>'role' else 'student' end,
    coalesce(
      new.raw_user_meta_data->>'NO MATRIK',
      new.raw_user_meta_data->>'no_matrik'
    )
  )
  on conflict (id) do nothing;
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
after insert on auth.users for each row execute procedure public.handle_new_user();

create table if not exists public.assignments (
  id bigint generated by default as identity primary key,
  title text not null,
  course text not null,
  instructions text,
  due_date date not null,
  xp_reward integer not null default 0 check (xp_reward >= 0),
  status text not null default 'Open',
  lecturer_id uuid references auth.users(id),
  created_at timestamptz not null default now()
);

create table if not exists public.submissions (
  id bigint generated by default as identity primary key,
  assignment_id bigint not null references public.assignments(id) on delete cascade,
  student_user_id uuid not null references auth.users(id) on delete cascade,
  "NO MATRIK" text not null references public.profiles("NO MATRIK") on update cascade,
  file_path text not null,
  return_file_path text,
  note text,
  score numeric(5,2) check (score between 0 and 100),
  grade text,
  feedback text,
  status text not null default 'Submitted',
  submitted_at timestamptz not null default now(),
  graded_at timestamptz,
  unique (assignment_id, "NO MATRIK")
);

create table if not exists public.materials (
  id bigint generated by default as identity primary key,
  title text not null,
  course text not null,
  chapter integer check (chapter in (1, 2, 5, 8, 9, 10)),
  material_type text check (
    material_type in ('Infographic','Notes','Exercise','Extra','Reference','Other')
  ),
  type text,
  file_path text not null,
  lecturer_id uuid references auth.users(id),
  uploaded_at timestamptz not null default now()
);

-- Configurable XP catalogue. Manual rules are awarded by lecturers/admins;
-- automatic rules are awarded only by dedicated, server-verified functions.
create table if not exists public.xp_rules (
  code text primary key,
  name text not null,
  description text not null,
  award_mode text not null check (award_mode in ('manual','automatic')),
  default_points integer not null check (default_points > 0),
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

insert into public.xp_rules (code, name, description, award_mode, default_points)
values
  ('consultation', 'Consultation', 'Constructive academic consultation outside normal class activity.', 'manual', 20),
  ('class_participation', 'Class participation', 'Meaningful contribution during a class session.', 'manual', 10),
  ('discipline', 'Discipline and professionalism', 'Consistent discipline, punctuality or professional conduct.', 'manual', 10),
  ('quiz_completion', 'In-app quiz', 'Successfully completed in-app quiz.', 'automatic', 25),
  ('earliest_submission', 'Earliest valid submission', 'First valid submission received for an assignment.', 'automatic', 30)
on conflict (code) do nothing;

-- Immutable XP ledger. stud_xp."XP" is the current balance; every ledger
-- entry explains one change and prevents the same automatic award recurring.
create table if not exists public.xp_events (
  id bigint generated by default as identity primary key,
  "NO MATRIK" text not null references public.profiles("NO MATRIK") on update cascade,
  rule_code text not null references public.xp_rules(code),
  points integer not null check (points <> 0),
  source_id text not null,
  reason text not null,
  award_mode text not null check (award_mode in ('manual','automatic','adjustment')),
  awarded_by uuid references auth.users(id),
  created_at timestamptz not null default now(),
  unique ("NO MATRIK", rule_code, source_id)
);

insert into storage.buckets (id, name, public)
values ('submissions', 'submissions', false), ('materials', 'materials', false)
on conflict (id) do nothing;

alter table public.profiles enable row level security;
alter table public.assignments enable row level security;
alter table public.submissions enable row level security;
alter table public.materials enable row level security;
alter table public.xp_rules enable row level security;
alter table public.xp_events enable row level security;
alter table public.stud_xp enable row level security;

grant select, insert, update, delete on table
  public.profiles,
  public.assignments,
  public.submissions,
  public.materials
to authenticated;
grant select on table public.xp_events to authenticated;
grant select on table public.xp_rules to authenticated;
grant insert, update, delete on table public.xp_rules to authenticated;
grant select on table public.stud_xp to authenticated;
grant usage, select on sequence
  public.assignments_id_seq,
  public.submissions_id_seq,
  public.materials_id_seq
to authenticated;

create or replace function public.current_role() returns text
language sql stable security definer set search_path = public
as $$ select role from public.profiles where id = auth.uid() $$;

-- All XP balance changes flow through this trigger. Clients never update
-- stud_xp directly.
create or replace function public.apply_xp_event() returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  update public.stud_xp
  set "XP" = coalesce("XP", 0) + new.points,
      updated_at = now()
  where "NO MATRIK" = new."NO MATRIK";

  if not found then
    raise exception 'No stud_xp row found for NO MATRIK %', new."NO MATRIK";
  end if;
  return new;
end;
$$;

drop trigger if exists on_xp_event_created on public.xp_events;
create trigger on_xp_event_created
after insert on public.xp_events
for each row execute procedure public.apply_xp_event();

-- Lecturer/admin award for consultation, participation, discipline, etc.
create or replace function public.award_manual_xp(
  p_no_matrik text,
  p_rule_code text,
  p_reason text,
  p_points_override integer default null,
  p_reference text default null
) returns bigint
language plpgsql
security definer
set search_path = public
as $$
declare
  v_event_id bigint;
  v_points integer;
begin
  if coalesce(public.current_role(), '') not in ('lecturer','admin') then
    raise exception 'Only lecturers and administrators can award XP';
  end if;

  if not exists (
    select 1 from public.profiles
    where "NO MATRIK" = p_no_matrik and role = 'student'
  ) then
    raise exception 'No student profile found for NO MATRIK %', p_no_matrik;
  end if;

  select coalesce(p_points_override, default_points)
  into v_points
  from public.xp_rules
  where code = p_rule_code and award_mode = 'manual' and active;

  if v_points is null or v_points <= 0 or v_points > 1000 then
    raise exception 'Invalid or inactive manual XP rule/points';
  end if;

  insert into public.xp_events (
    "NO MATRIK", rule_code, points, source_id, reason, award_mode, awarded_by
  )
  values (
    p_no_matrik,
    p_rule_code,
    v_points,
    coalesce(nullif(p_reference, ''), gen_random_uuid()::text),
    p_reason,
    'manual',
    auth.uid()
  )
  returning id into v_event_id;

  return v_event_id;
end;
$$;

revoke all on function public.award_manual_xp(text, text, text, integer, text) from public;
revoke execute on function public.award_manual_xp(text, text, text, integer, text) from anon;
grant execute on function public.award_manual_xp(text, text, text, integer, text) to authenticated;

-- Automatic award for the first authenticated student who has a valid
-- submission for an assignment. Repeated calls are idempotent.
create or replace function public.award_earliest_submission_xp(
  p_assignment_id bigint
) returns integer
language plpgsql
security definer
set search_path = public
as $$
declare
  v_no_matrik text;
  v_first_user uuid;
  v_points integer;
  v_inserted integer := 0;
begin
  select "NO MATRIK" into v_no_matrik
  from public.profiles
  where id = auth.uid() and role = 'student';

  if v_no_matrik is null then
    raise exception 'A linked student profile is required';
  end if;

  select student_user_id into v_first_user
  from public.submissions
  where assignment_id = p_assignment_id
    and status in ('Submitted','Graded')
  order by submitted_at asc, id asc
  limit 1;

  if v_first_user is distinct from auth.uid() then
    return 0;
  end if;

  select default_points into v_points
  from public.xp_rules
  where code = 'earliest_submission' and award_mode = 'automatic' and active;

  if v_points is null then
    return 0;
  end if;

  insert into public.xp_events (
    "NO MATRIK", rule_code, points, source_id, reason, award_mode, awarded_by
  )
  values (
    v_no_matrik,
    'earliest_submission',
    v_points,
    p_assignment_id::text,
    'First valid assignment submission',
    'automatic',
    null
  )
  on conflict ("NO MATRIK", rule_code, source_id) do nothing;

  get diagnostics v_inserted = row_count;
  return case when v_inserted = 1 then v_points else 0 end;
end;
$$;

revoke all on function public.award_earliest_submission_xp(bigint) from public;
revoke execute on function public.award_earliest_submission_xp(bigint) from anon;
grant execute on function public.award_earliest_submission_xp(bigint) to authenticated;

drop policy if exists "profiles_read" on public.profiles;
create policy "profiles_read" on public.profiles for select to authenticated
using (id = auth.uid() or public.current_role() in ('lecturer','admin'));
drop policy if exists "profiles_admin_write" on public.profiles;
create policy "profiles_admin_write" on public.profiles for all to authenticated
using (public.current_role() = 'admin') with check (public.current_role() = 'admin');

drop policy if exists "assignments_read" on public.assignments;
create policy "assignments_read" on public.assignments for select to authenticated using (true);
drop policy if exists "assignments_staff_write" on public.assignments;
create policy "assignments_staff_write" on public.assignments for all to authenticated
using (public.current_role() in ('lecturer','admin')) with check (public.current_role() in ('lecturer','admin'));

drop policy if exists "submissions_read" on public.submissions;
create policy "submissions_read" on public.submissions for select to authenticated
using (student_user_id = auth.uid() or public.current_role() in ('lecturer','admin'));
drop policy if exists "submissions_student_insert" on public.submissions;
create policy "submissions_student_insert" on public.submissions for insert to authenticated
with check (
  student_user_id = auth.uid()
  and "NO MATRIK" = (
    select p."NO MATRIK" from public.profiles p where p.id = auth.uid()
  )
);
drop policy if exists "submissions_staff_update" on public.submissions;
create policy "submissions_staff_update" on public.submissions for update to authenticated
using (public.current_role() in ('lecturer','admin'));

drop policy if exists "materials_read" on public.materials;
create policy "materials_read" on public.materials for select to authenticated using (true);
drop policy if exists "materials_staff_write" on public.materials;
create policy "materials_staff_write" on public.materials for all to authenticated
using (public.current_role() in ('lecturer','admin')) with check (public.current_role() in ('lecturer','admin'));

drop policy if exists "xp_rules_read" on public.xp_rules;
create policy "xp_rules_read" on public.xp_rules for select to authenticated using (true);
drop policy if exists "xp_rules_admin_write" on public.xp_rules;
create policy "xp_rules_admin_write" on public.xp_rules for all to authenticated
using (public.current_role() = 'admin') with check (public.current_role() = 'admin');

drop policy if exists "xp_events_read" on public.xp_events;
create policy "xp_events_read" on public.xp_events for select to authenticated
using (
  "NO MATRIK" = (
    select p."NO MATRIK" from public.profiles p where p.id = auth.uid()
  )
  or public.current_role() in ('lecturer','admin')
);

drop policy if exists "stud_xp_read" on public.stud_xp;
create policy "stud_xp_read" on public.stud_xp for select to authenticated
using (
  "NO MATRIK" = (
    select p."NO MATRIK" from public.profiles p where p.id = auth.uid()
  )
  or public.current_role() in ('lecturer','admin')
);

drop policy if exists "submission_files" on storage.objects;
create policy "submission_files" on storage.objects for all to authenticated
using (bucket_id = 'submissions' and (auth.uid()::text = (storage.foldername(name))[1] or public.current_role() in ('lecturer','admin')))
with check (bucket_id = 'submissions' and (auth.uid()::text = (storage.foldername(name))[1] or public.current_role() in ('lecturer','admin')));
drop policy if exists "material_files_read" on storage.objects;
create policy "material_files_read" on storage.objects for select to authenticated using (bucket_id = 'materials');
drop policy if exists "material_files_write" on storage.objects;
create policy "material_files_write" on storage.objects for all to authenticated
using (bucket_id = 'materials' and public.current_role() in ('lecturer','admin'))
with check (bucket_id = 'materials' and public.current_role() in ('lecturer','admin'));
