-- XPLMS migration 021
-- Student quiz-question reports with audited Admin score and XP correction.
-- Run once in Supabase SQL Editor after migration 020.

begin;

alter table public.quiz_attempts
  add column if not exists question_snapshot jsonb not null default '[]'::jsonb;

create table if not exists public.quiz_question_reports (
  id bigint generated by default as identity primary key,
  attempt_id bigint not null references public.quiz_attempts(id) on delete cascade,
  question_id bigint not null references public.quiz_questions(id) on delete restrict,
  student_user_id uuid not null references public.app_users(id) on delete cascade,
  "NO MATRIK" text not null,
  chapter integer not null,
  student_answer integer check (student_answer between 0 and 3),
  question_snapshot jsonb not null,
  report_reason text not null check (
    report_reason in (
      'incorrect_answer', 'unclear_question', 'duplicate_options',
      'formatting_error', 'other'
    )
  ),
  student_notes text,
  status text not null default 'pending' check (
    status in ('pending', 'accepted', 'rejected')
  ),
  admin_notes text,
  reviewed_by uuid references public.app_users(id) on delete set null,
  reviewed_at timestamptz,
  original_correct_count integer,
  corrected_correct_count integer,
  original_xp integer,
  corrected_xp integer,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (attempt_id, question_id)
);

create index if not exists quiz_question_reports_status_created_idx
  on public.quiz_question_reports (status, created_at desc);
create index if not exists quiz_question_reports_student_idx
  on public.quiz_question_reports ("NO MATRIK", created_at desc);

alter table public.quiz_question_reports enable row level security;
revoke all on table public.quiz_question_reports from anon, authenticated;

create or replace function public.resolve_quiz_question_report(
  p_report_id bigint,
  p_status text,
  p_admin_notes text,
  p_corrected_correct_count integer,
  p_reviewed_by uuid
)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  report_row public.quiz_question_reports%rowtype;
  attempt_row public.quiz_attempts%rowtype;
  v_corrected_count integer;
  v_corrected_score numeric;
  v_corrected_xp integer;
begin
  if p_status not in ('accepted', 'rejected') then
    raise exception 'Resolution status must be accepted or rejected';
  end if;

  select * into report_row
  from public.quiz_question_reports
  where id = p_report_id
  for update;
  if not found then
    raise exception 'Quiz question report % was not found', p_report_id;
  end if;
  if report_row.status <> 'pending' then
    raise exception 'Quiz question report % is already resolved', p_report_id;
  end if;

  select * into attempt_row
  from public.quiz_attempts
  where id = report_row.attempt_id
  for update;
  if not found then
    raise exception 'Quiz attempt % was not found', report_row.attempt_id;
  end if;

  v_corrected_count := attempt_row.correct_count;
  if p_status = 'accepted' and p_corrected_correct_count is not null then
    v_corrected_count := greatest(
      0, least(p_corrected_correct_count, attempt_row.total_questions)
    );
  end if;
  v_corrected_score := case
    when attempt_row.total_questions > 0
      then v_corrected_count::numeric / attempt_row.total_questions * 100
    else 0
  end;
  v_corrected_xp := 5 + v_corrected_count;

  if p_status = 'accepted' then
    update public.quiz_attempts
    set correct_count = v_corrected_count,
        score = v_corrected_score,
        passed = v_corrected_score >= 60,
        xp_awarded = v_corrected_xp
    where id = attempt_row.id;

    if attempt_row.xp_event_id is not null then
      update public.xp_events
      set points = v_corrected_xp,
          reason = concat(
            'Corrected daily C', attempt_row.chapter, ' quiz: ',
            v_corrected_count, '/', attempt_row.total_questions,
            ' correct after question report ', p_report_id
          )
      where id = attempt_row.xp_event_id;
    end if;
  end if;

  update public.quiz_question_reports
  set status = p_status,
      admin_notes = nullif(trim(p_admin_notes), ''),
      reviewed_by = p_reviewed_by,
      reviewed_at = now(),
      original_correct_count = attempt_row.correct_count,
      corrected_correct_count = v_corrected_count,
      original_xp = attempt_row.xp_awarded,
      corrected_xp = v_corrected_xp,
      updated_at = now()
  where id = p_report_id;
end;
$$;

revoke all on function public.resolve_quiz_question_report(
  bigint, text, text, integer, uuid
) from public, anon, authenticated;
grant execute on function public.resolve_quiz_question_report(
  bigint, text, text, integer, uuid
) to service_role;

commit;
